---
new_page_extension: md
auto_deploy: false
admin_path: "/assets/admin"
webhook_url: 
sections:
- type: directory
  path: src/routes/blog
  label: Voyages
  create: documents
  match: "**/*.md"
  templates:
  - article
upload_dir: public/img
public_path: https://amelie-voyages.netlify.app/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
